server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/streetartlive
spring.datasource.username=postgres
spring.datasource.password=gugugaga
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=3000


cloudinary.cloud-name=djmzapvyv
cloudinary.api-key=831785859966723
cloudinary.api-secret=QZTDUR2Sng0aCNrZx9B8ifQVhLQ